[book]
authors = ["Tandem Team"]
language = "en"

src = "src"
title = "Tandem Engine Guide"

[output.html]
git-repository-url = "https://github.com/frumu-ai/tandem"
edit-url-template = "https://github.com/frumu-ai/tandem/edit/main/guide/{path}"
